[project]
name = "dzenq"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.6,<3.13"
dependencies = [
    "keri>=1.3.4",
    "pysodium>=0.7.18",
    "pytest>=9.0.2",
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]
